name: Build Karbon and Release

on:
  push:
    branches:
      - main
      - fix/cross-platform-upload

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            extension: .exe
            pyinstaller-args: --onefile --noconsole --name Karbon --icon=icon.ico
          - os: ubuntu-latest
            extension: ""
            pyinstaller-args: --onefile --noconsole --name Karbon
          - os: macos-latest
            extension: .app
            pyinstaller-args: --onedir --noconsole --name Karbon

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create and activate virtual environment
        shell: bash
        run: |
          python -m venv venv
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Install dependencies
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --no-cache-dir pyinstaller || { echo "Failed to install PyInstaller"; exit 1; }
          python -m pip install -r requirements.txt || true

      - name: Debug PyInstaller installation
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          echo "Python path: $(which python)"
          python --version
          echo "Pip path: $(which pip)"
          pip --version
          pip list | grep pyinstaller || echo "PyInstaller not listed in pip"
          python -m pyinstaller --version || { echo "PyInstaller module not found"; exit 1; }

      - name: Build executable with PyInstaller
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            source venv/Scripts/activate
          else
            source venv/bin/activate
          fi
          python -m pyinstaller ui.py ${{ matrix.pyinstaller-args }}

      - name: Rename binary for upload
        shell: bash
        run: |
          mkdir -p upload
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp -r "dist/Karbon.app" "upload/Karbon-${{ runner.os }}.app"
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp "dist/Karbon.exe" "upload/Karbon-${{ runner.os }}.exe"
          else
            cp "dist/Karbon" "upload/Karbon-${{ runner.os }}"
          fi

      - name: Get short commit hash
        id: vars
        shell: bash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "build-${{ env.SHORT_SHA }}"
          name: "Karbon Build ${{ env.SHORT_SHA }}"
          draft: false
          prerelease: false
          files: upload/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
